working on perturbation detectors
Giskard-AI/giskard-vision pull request #51
Opened 2024-08-08 14:03 UTC by rabah-khalek

2024-08-12 08:23 UTC, bmalezieux requested changes
We can also add a NoisePerturbationDetector to evaluate robustness to noise

2024-08-12 08:23 UTC, bmalezieux commented on giskard_vision/core/detectors/perturbation.py
> +from giskard_vision.landmark_detection.tests.base import TestDiff
I think we should move TestDiff in core instead of importing it from landmark_detection

2024-08-12 10:54 UTC, rabah-khalek commented on giskard_vision/core/detectors/perturbation.py
> +                )
ideally a bunch of values in the range of [0.1, 0.8] would be nice yes

2024-08-12 10:54 UTC, rabah-khalek commented on giskard_vision/core/detectors/perturbation.py
> +        relative_delta = (test_result.metric_value_test - test_result.metric_value_ref) / test_result.metric_value_ref
agreed

2024-08-12 13:27 UTC, bmalezieux commented on giskard_vision/core/detectors/perturbation.py
> +                )
Actually this is only to save the transformed images in order to display them in the report

2024-08-13 11:16 UTC, rabah-khalek commented on giskard_vision/core/detectors/perturbation.py
> +        relative_delta = (test_result.metric_value_test - test_result.metric_value_ref) / test_result.metric_value_ref
taken care of in https://github.com/Giskard-AI/giskard-vision/pull/53

2024-08-13 11:59 UTC, merged